Implemented small change to markdown formatting, and added docs
StanfordSpezi/SpeziViews pull request #34
Opened 2024-03-05 21:48 UTC by auddithio

# *Name of the PR*

## :recycle: Current situation & Problem
The current SpeziViews module were not all well documented equally, as per the documentation requirements set forth in the [Stanford Spezi Documentation Guide.](https://swiftpackageindex.com/stanfordspezi/spezi/1.2.1/documentation/spezi/documentation-guide#Landing-Page). Also, the markdown formatting was restricted to `inlineOnly` changes, which would not render formatting for larger changes like titles, which is the issue our app's consent doc ran into.

## :gear: Release Notes 
- Changed markdown formatting to `.full` to incorporate the full breadth of document markdowns
- Added documentation for the Localizable strings section in text

## :books: Documentation
- Added documentation is line with the [Spezi Documentation Guide](https://swiftpackageindex.com/stanfordspezi/spezi/1.2.1/documentation/spezi/documentation-guide#Landing-Page)

## :white_check_mark: Testing
- For the markdown formatting, used the `AttributedString` framework to render markdown documents locally, and it seemed to render properly. Not sure what edge cases the Spezi team wanted to account for by setting it to `inline`, so further testing for the full template application is needed.

## :pencil: Code of Conduct & Contributing Guidelines 

By submitting creating this pull request, you agree to follow our [Code of Conduct](https://github.com/StanfordSpezi/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/StanfordSpezi/.github/blob/main/CONTRIBUTING.md):
- [x] I agree to follow the [Code of Conduct](https://github.com/StanfordSpezi/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/StanfordSpezi/.github/blob/main/CONTRIBUTING.md).

2024-03-06 19:14 UTC, Supereg requested changes
Thank you for improving the documentation of SpeziViews. Thanks for the PR.

I only had small comment regarding a code example on one of the documentation blocks. Otherwise, the PR looks good 👍

2024-03-06 19:14 UTC, Supereg commented on Sources/SpeziViews/Views/Text/MarkdownView.swift
> +    ///    *This should be italiced* and **this bolded**").utf8
If this is a code example, make sure to wrap them into markdown `swift` code block, as you did for the `TextContent´ type as well.
This makes sure that inline code appears with proper syntax highlighting. Make sure to properly format the code according to your swiftlint code style rules.

2024-03-15 00:54 UTC, auddithio commented
made some changes based on feedback and after talking to Spezi staff!

2024-03-22 23:04 UTC, PSchmiedmayer requested changes
@auddithio Thank you for the PR; I had a few further comments and suggestions that would need to be addressed before we merge the PR 👍

2024-03-22 23:04 UTC, PSchmiedmayer commented on Sources/SpeziViews/Views/Text/MarkdownView.swift
> +    ///    ```
This code example does not compile, if you want to create a String with line breaks you will have to use a multi-line string interval: https://docs.swift.org/swift-book/documentation/the-swift-programming-language/stringsandcharacters/#Multiline-String-Literals

In addition, the code example does not call the API.

Comments like `//Example` should be removed and I would suggest to rather add an explanation around the example block.

Last but not least, I would move the example above the parameters section of the code documentation.

2024-03-22 23:04 UTC, PSchmiedmayer commented on Sources/SpeziViews/Views/Text/MarkdownView.swift
> +                options: .init(interpretedSyntax: .inlineOnly)
What is the reason for this change? Wouldn't it make sense to switch to `.full`?

2024-03-22 23:04 UTC, PSchmiedmayer commented on Sources/SpeziViews/Views/Text/TextContent.swift
> +/// ```
Thank you for the added documentation!

The same comments about the example also apply here as well.

2024-07-18 00:28 UTC, closed without merging